### ISSUE TITLE
Cannot install Sunshine Virtual Monitor - OSError: Sunshine is not installed

### ISSUE THREAD

**Issue by Mikolaj-Walkowiak** [Nonary/PlayNiteWatcher#12]
`Traceback (most recent call last):
  File "C:\Users\Work\AppData\Local\Temp\ONEFIL~1\main.py", line 7, in <module>
  File "C:\Users\Work\AppData\Local\Temp\ONEFIL~1\misc\MenuHandler.py", line 214, in print_menu
  File "C:\Users\Work\AppData\Local\Temp\ONEFIL~1\misc\MenuHandler.py", line 205, in _execute_selection
  File "C:\Users\Work\AppData\Local\Temp\ONEFIL~1\misc\MenuHandler.py", line 39, in <lambda>
  File "C:\Users\Work\AppData\Local\Temp\ONEFIL~1\misc\Config.py", line 355, in download_svm
  File "C:\Users\Work\AppData\Local\Temp\ONEFIL~1\misc\Config.py", line 120, in configure_sunshine
  File "C:\Users\Work\AppData\Local\Temp\ONEFIL~1\misc\Config.py", line 39, in _reset_global_prep_cmd
OSError: Sunshine is not installed.`

I have it installed on the D: drive, I suppose that's the problem?

**Comment by Nonary** [comment]
I'm not even using python in my code here, did you open this issue on the wrong repository?

**Comment by Nonary** [comment]
Oh I found it, you must be talking about https://github.com/Cynary/sunshine-virtual-monitor

I don't manage that repository at all, so you would need to open an issue there to report this problem.
